- .gitignore
- Web/.gitignore
- Web/package.json
- Web/pages/_app.tsx
- Web/pages/api/status.tsx
- Web/pages/index.tsx
- Web/yarn.lock
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> Add front firebase

- .gitignore
- Backend/firebase.py
- Backend/geekcamp.sample.json
- Backend/requirements.txt
https://gakogako.com/python_firestore/
firebaseへの接続
データベース定義及びビーコン情報の送信
```
pip install -r requirements.txt 
```
```
python firebase.py
```
あくまで目安です。
- 想定通りに動作するか？
- etc...
現時点ではyahooから最新ニュースを取り出しfirebaseに保存する
> add:firebase接続

- Backend/firebase.py
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> add:firebase定義

- Web/components/NavigateBar.tsx
- Web/package.json
- Web/pages/api/status.tsx
- Web/pages/index.tsx
- Web/yarn.lock
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> add: styled-components削除,navbarの追加

- Web/components/CountDisplay.tsx
- Web/components/NavigateBar.tsx
- Web/components/UserDisplay.tsx
- Web/package.json
- Web/pages/index.tsx
- Web/styles/globals.css
- Web/tsconfig.json
- Web/yarn.lock
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> recoilによる値渡し処理の追加を行う

- Client/app/src/main/AndroidManifest.xml
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/service/BeaconApplication.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/service/IbeaconInputService.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/service/StopIbeaconServiseReceiver.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/ui/home/HomeFragment.kt
- Client/app/src/main/res/values/strings.xml
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> update: URLの更新

- Client/app/src/main/java/io/github/com/harutiro/tempmanager/ui/home/HomeFragment.kt
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> update: 範囲指定をして、画面のサイズで表示されるように指定

- Backend/beacon_send/beacon.py
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> add:firebase

- Client/app/build.gradle
- Client/app/src/main/AndroidManifest.xml
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/MainActivity.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/service/IbeaconOutputService.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/service/StopIbeaconForegroundReceiver.kt
Foregroundを用いてibeaconの出力をおこなった。
消費電力などの設定はまだ
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> ibeaconの出力部分完成

- Client/app/build.gradle
- Client/app/src/main/AndroidManifest.xml
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/MainActivity.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/TempEditAcitivity.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/service/IbeaconOutputService.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/ui/setting/SettingFragment.kt
- Client/app/src/main/res/drawable/device_thermostat_fill0_wght400_grad0_opsz48.xml
- Client/app/src/main/res/layout/activity_temp_edit_acitivity.xml
- Client/app/src/main/res/layout/fragment_notifications.xml
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> Add ibeacon input

- Backend/beacon_send/beacon.py
- Backend/firebase.py
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> fix:発火処理の時間修正

- Client/app/src/main/java/io/github/com/harutiro/tempmanager/MainActivity.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/service/IbeaconOutputService.kt
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> サービスが終了した時にビーコンを止めるように変更

- Backend/firebase.py
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> fix: python側を5分毎にfirebaseへ出力する

- Client/app/src/main/java/io/github/com/harutiro/tempmanager/TempEditAcitivity.kt
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> update: 戻るボタンでアクティビティが閉じるのを防止

- Client/build.gradle
- Client/gradle/wrapper/gradle-wrapper.properties
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> upgrade: Androidのバージョンアップ

- LICENCE.md
- README.md
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> Add readmemd

- Client/app/build.gradle
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/MainActivity.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/TempEditAcitivity.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/WelcomeActivity.kt
- Client/app/src/main/res/layout/activity_main.xml
- Client/app/src/main/res/values-night/colors.xml
- Client/app/src/main/res/values/colors.xml
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> パーミッション設定を行った。

- Client/app/src/main/java/io/github/com/harutiro/tempmanager/welcome_ui/acount/ui/login/AcountFragment.kt
- Client/app/src/main/res/layout/fragment_acount.xml
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> update: 正規表現をして、正しくないフォーマットを保存できなくした。

- Client/app/src/main/java/io/github/com/harutiro/tempmanager/TempEditAcitivity.kt
- Client/app/src/main/res/layout/activity_temp_edit_acitivity.xml
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> update: 正規表現をして、Tempの方の正しくないフォーマットを保存できなくした。

- Client/app/src/main/java/io/github/com/harutiro/tempmanager/MainActivity.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/TempEditAcitivity.kt
- Client/app/src/main/java/io/github/com/harutiro/tempmanager/WelcomeActivity.kt
このPR内でやったことを書く
テスト項目、テスト方法を書く
あくまで目安です。
- 想定通りに動作するか？
- etc...
> Upgrade smoll bug change
